# Generated by Django 3.1.5 on 2021-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Computers', 'Computers'), ('Laptops', 'Laptops'), ('Phones', 'Phones'), ('Monitors', 'Monitors'), ('SSD', 'SSD'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Video graphics', 'Video graphics'), ('Coolers', 'Coolers'), ('System blocks', 'System blocks')], max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
