# Generated by Django 3.1.5 on 2021-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210118_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Monitor', 'Monitor'), ('SSD', 'SSD'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Graphic card', 'Graphic card'), ('Cooler', 'Cooler'), ('System block', 'System block')], max_length=50),
        ),
    ]
