# Generated by Django 3.1.5 on 2021-01-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_file',
        ),
    ]
