# Generated by Django 3.1.5 on 2021-01-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210122_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_product.png', null=True, upload_to=''),
        ),
    ]
