# Generated by Django 3.1.5 on 2021-01-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='client',
            new_name='manager',
        ),
    ]
